import test from 'node:test';
import assert from 'node:assert/strict';
import {newAlphaLabState,observeAlphaScan,alphaAttributionSummary,replayHistoricalAlphaScans} from '../research/alpha-attribution-r43.js';

const H=3600000;
const candidate=(symbol,price,technical=80)=>({symbol,price,side:'LONG',status:'READY',technical,candidate:technical+2,distanceAtr:.4,frames:{
  '15m':{ema20:101,ema50:100,rsi:60,macdHist:1,atr:2,volumeRatio:1.2},'1h':{ema20:102,ema50:100,rsi:62,macdHist:2,atr:4,adx:25},'4h':{ema20:104,ema50:100,adx:28}}});

test('R43 captures one neutral observation per symbol and four-hour bucket',()=>{let s=newAlphaLabState(0,{feeBps:5,slippageBps:3});s=observeAlphaScan(s,[candidate('BTCUSDT',100)],0);s=observeAlphaScan(s,[candidate('BTCUSDT',101)],H);assert.equal(s.observations.length,1);assert.equal(s.policy.roundTripCostBps,16);assert.equal(s.executionImpact,false);});
test('R43 labels only the due horizon and rejects late proxy prices',()=>{let s=newAlphaLabState(0,{feeBps:5,slippageBps:3});s=observeAlphaScan(s,[candidate('BTCUSDT',100)],0);s=observeAlphaScan(s,[candidate('BTCUSDT',102)],24*H);const first=s.observations[0];assert.equal(first.outcomes.h4.valid,false);assert.equal(first.outcomes.h4.reason,'LABEL_WINDOW_MISSED');assert.equal(first.outcomes.h12.valid,false);assert.equal(first.outcomes.h24.valid,true);assert.equal(first.outcomes.h24.netBps,184);assert.equal(s.observations.length,2);});
test('R43 summary remains research-only and cannot auto-promote',()=>{let s=newAlphaLabState(0,{feeBps:5,slippageBps:3});s=observeAlphaScan(s,[candidate('BTCUSDT',100)],0);const x=alphaAttributionSummary(s);assert.equal(x.state,'BUILDING_FORWARD_LABELS');assert.equal(x.legacyScore.verdict,'REJECTED');assert.equal(x.autoPromotion,false);assert.equal(x.executionImpact,false);assert.equal(x.coverage.observations,1);});
test('R43 never turns null telemetry into an invented zero feature',()=>{let s=newAlphaLabState(0);const c=candidate('BTCUSDT',100);c.technical=null;c.frames['1h'].rsi=null;s=observeAlphaScan(s,[c],0);assert.equal(s.observations[0].features.technical,null);assert.equal(s.observations[0].features.rsi1h,null);});
test('R44 timer projects the first attribution check while telemetry is live',()=>{let s=newAlphaLabState(0,{feeBps:5,slippageBps:3});s=observeAlphaScan(s,[candidate('BTCUSDT',100),candidate('ETHUSDT',100),candidate('SOLUSDT',100)],0);const x=alphaAttributionSummary(s,0);assert.equal(x.timer.dataStatus,'LIVE');assert.equal(x.timer.nextSampleAt,new Date(4*H).toISOString());assert.equal(x.timer.nextLabelAt,new Date(24*H).toISOString());assert.equal(x.timer.evaluationAt,new Date(156*H).toISOString());assert.equal(x.timer.labelsRemaining,100);assert.equal(x.timer.factorHypothesisFound,false);});
test('R44 timer stops claiming an ETA when scanner telemetry is stale',()=>{let s=newAlphaLabState(0);s=observeAlphaScan(s,[candidate('BTCUSDT',100)],0);const x=alphaAttributionSummary(s,16*60*1000);assert.equal(x.timer.dataStatus,'STALE');assert.equal(x.timer.nextSampleAt,null);assert.equal(x.timer.nextLabelAt,null);assert.equal(x.timer.evaluationAt,null);});
test('an empty scan attempt cannot falsely refresh stale market telemetry',()=>{let s=newAlphaLabState(0);s=observeAlphaScan(s,[candidate('BTCUSDT',100)],0);s=observeAlphaScan(s,[],20*60*1000);assert.equal(s.updatedAt,new Date(0).toISOString());assert.equal(s.lastAttemptAt,new Date(20*60*1000).toISOString());assert.equal(alphaAttributionSummary(s,20*60*1000).timer.dataStatus,'STALE');});
test('historical replay stays separate and requires chronological closed-candle inputs',()=>{const scans=[{at:0,closedCandles:true,candidates:[candidate('BTCUSDT',100)]},{at:24*H,closedCandles:true,candidates:[candidate('BTCUSDT',102)]}];const replay=replayHistoricalAlphaScans(scans,{feeBps:5,slippageBps:3},24*H);assert.equal(replay.summary.mode,'HISTORICAL_REPLAY');assert.equal(replay.summary.independentFromForward,true);assert.equal(replay.state.observations[0].source,'HISTORICAL_REPLAY');assert.throws(()=>replayHistoricalAlphaScans([{at:H,closedCandles:false,candidates:[]}],{},H),/closed-candle/);assert.throws(()=>replayHistoricalAlphaScans([{at:2*H,closedCandles:true,candidates:[]},{at:H,closedCandles:true,candidates:[]}],{},2*H),/chronological/);});
