import test from 'node:test';
import assert from 'node:assert/strict';
import { PROTOCOL, BridgeGuardError, validateRequest, reconcileRequest, validateAck, validateDraftPr, advance } from '../scripts/codex-bridge-contract.mjs';
const A='8a8a43fc8df4e440294bf7ef5747510b6c6a44d0',B='b'.repeat(40),C='c'.repeat(40);
const base=()=>({protocol:PROTOCOL,requestId:'CODEX-BRIDGE-V2-001',opId:'BRIDGE-V2-OP-001',expectedMain:A,expectedBase:A,expectedHead:A,targetBranch:'feat/codex-bridge-v2-contract-20261009',model:'gpt-5.3-codex',allowedPaths:['scripts/codex-bridge-contract.mjs'],allowedActions:['offline_code','draft_pr'],researchStage:'SOURCE_AUDIT',costGuard:{overageAllowed:false,additionalSpendAllowed:false},forbidden:['merge','workflow','trading']});
const fail=(fn,code)=>assert.throws(fn,e=>e instanceof BridgeGuardError && e.code===code);
const ack=()=>({protocol:PROTOCOL,requestId:base().requestId,opId:base().opId,expectedHead:A,expectedBase:A,agentActor:'github-copilot',model:base().model,result:'ACCEPTED',mutations:0});
const observed=()=>({authenticatedBy:'github-api',trustedSource:true,actor:'github-copilot',url:'https://github.com/Achi1984/meridian/issues/627',requestId:base().requestId,opId:base().opId,model:base().model,liveMain:A});
const step=(state,next,evidence)=>advance({state,request:base(),headSha:B},{next,requestId:base().requestId,expectedHead:A,evidence});

test('valid immutable offline request returns digest',()=>assert.match(validateRequest(base()).fingerprint,/^[a-f0-9]{64}$/));
test('same request is replay-safe and inert',()=>assert.equal(reconcileRequest(base(),base()).status,'IDENTICAL_REPLAY_NO_ACTION'));
test('changed model on same id is a hard conflict',()=>fail(()=>reconcileRequest(base(),{...base(),model:'other'}),'DUPLICATE_SCOPE_CONFLICT'));
test('unrelated request is distinct',()=>assert.equal(reconcileRequest(base(),{...base(),requestId:'CODEX-BRIDGE-V2-002'}).status,'NEW_REQUEST'));
test('invalid head fails closed',()=>fail(()=>validateRequest({...base(),expectedHead:'123'}),'REQUEST_SHA_INVALID'));
test('invalid research stage fails closed',()=>fail(()=>validateRequest({...base(),researchStage:'PAPER'}),'RESEARCH_STAGE_FORBIDDEN'));
test('cannot target main',()=>fail(()=>validateRequest({...base(),targetBranch:'main'}),'BRANCH_NOT_ISOLATED'));
test('missing cost lockout fails',()=>fail(()=>validateRequest({...base(),costGuard:{overageAllowed:true,additionalSpendAllowed:false}}),'COST_GUARD_MISSING'));
test('workflow path disallowed',()=>fail(()=>validateRequest({...base(),allowedPaths:['.github/workflows/run.yml']}),'PATH_SCOPE_INVALID'));
test('bad/duplicate path disallowed',()=>fail(()=>validateRequest({...base(),allowedPaths:['../secrets']}),'PATH_SCOPE_INVALID'));
test('unauthenticated ACK fails',()=>fail(()=>validateAck(base(),ack(),{...observed(),trustedSource:false}),'ACK_IDENTITY_UNVERIFIED'));
test('agent identity mismatch fails',()=>fail(()=>validateAck(base(),ack(),{...observed(),actor:'attacker'}),'ACK_ACTOR_CONFLICT'));
test('wrong model is rejected',()=>fail(()=>validateAck(base(),{...ack(),model:'default'},observed()),'ACK_MODEL_MISMATCH'));
test('stale main rejects ACK',()=>fail(()=>validateAck(base(),ack(),{...observed(),liveMain:C}),'MAIN_MOVED'));
test('side effects before ACK fail',()=>fail(()=>validateAck(base(),{...ack(),mutations:1},observed()),'ACK_SIDE_EFFECTS'));
test('verified ACK accepts',()=>assert.equal(validateAck(base(),ack(),observed()).validated,true));
test('unsolicited non-Draft PR rejected',()=>fail(()=>validateDraftPr(base(),{draft:false,state:'open',merged:false,baseSha:A,headRef:base().targetBranch,headSha:B,changedFiles:base().allowedPaths},{authenticatedBy:'github-api',trustedSource:true,liveMain:A,headSha:B}),'PR_NOT_DRAFT'));
test('changed PR base is rejected',()=>fail(()=>validateDraftPr(base(),{draft:true,state:'open',merged:false,baseSha:C,headRef:base().targetBranch,headSha:B,changedFiles:base().allowedPaths},{authenticatedBy:'github-api',trustedSource:true,liveMain:A,headSha:B}),'PR_BASE_CHANGED'));
test('extra PR file rejected',()=>fail(()=>validateDraftPr(base(),{draft:true,state:'open',merged:false,baseSha:A,headRef:base().targetBranch,headSha:B,changedFiles:['server.js']},{authenticatedBy:'github-api',trustedSource:true,liveMain:A,headSha:B}),'PR_SCOPE_DRIFT'));
test('unexpected head rejected',()=>fail(()=>validateDraftPr(base(),{draft:true,state:'open',merged:false,baseSha:A,headRef:base().targetBranch,headSha:B,changedFiles:base().allowedPaths},{authenticatedBy:'github-api',trustedSource:true,liveMain:A,headSha:C}),'PR_HEAD_MISMATCH'));
test('valid scoped draft accepted',()=>assert.equal(validateDraftPr(base(),{draft:true,state:'open',merged:false,baseSha:A,headRef:base().targetBranch,headSha:B,changedFiles:base().allowedPaths},{authenticatedBy:'github-api',trustedSource:true,liveMain:A,headSha:B}).headSha,B));
test('cannot assign without explicit owner approval transition',()=>fail(()=>step('PLANNED','ASSIGNED',{}),'TRANSITION_FORBIDDEN'));
test('cost attestation missing blocks authorization',()=>fail(()=>step('PLANNED','OWNER_AUTHORIZED',{owner:'Achi1984',approvalId:'approval-1',approvedHead:A,approvedModel:base().model,overageDisabledVerified:false,includedCreditsVerified:true,additionalSpendAllowed:false}),'COST_NOT_VERIFIED'));
test('authorization transition requires verified cost gates',()=>assert.equal(step('PLANNED','OWNER_AUTHORIZED',{owner:'Achi1984',approvalId:'approval-1',approvedHead:A,approvedModel:base().model,overageDisabledVerified:true,includedCreditsVerified:true,additionalSpendAllowed:false}).state,'OWNER_AUTHORIZED'));
test('CI alone never moves directly to merge decision',()=>fail(()=>step('DRAFT_PR','AWAITING_MERGE_DECISION',{}),'TRANSITION_FORBIDDEN'));
test('exact-head mismatch fails CI',()=>fail(()=>step('DRAFT_PR','CI_VERIFIED',{ciSuccess:true,headSha:C,runUrl:'https://github.com/runs/1'}),'CI_EXACT_HEAD_MISSING'));
test('review cannot waive independent execution',()=>fail(()=>step('CI_VERIFIED','CLAUDE_EXACT_HEAD_REVIEWED',{verdict:'GREEN_LIGHT',headSha:B,reviewUrl:'https://github.com/issues/1',independentExecutionProven:false}),'REVIEW_INSUFFICIENT'));
test('STOP requires recorded reason',()=>fail(()=>advance({state:'ACKED',request:base()},{next:'STOPPED'}),'STOP_REASON_MISSING'));
test('STOP is terminal',()=>fail(()=>step('STOPPED','PLANNED',{}),'TRANSITION_FORBIDDEN'));

test('malformed action array fails closed with typed error',()=>fail(()=>validateRequest({...base(),allowedActions:'offline_code,draft_pr'}),'ACTIONS_FORBIDDEN'));
test('forbidden-actions guard must be array',()=>fail(()=>validateRequest({...base(),forbidden:'merge workflow trading'}),'FORBIDDEN_ACTION_GAP'));
test('STOP cannot be repeated',()=>fail(()=>advance({state:'STOPPED',request:base()},{next:'STOPPED',reason:'repeat'}),'TRANSITION_FORBIDDEN'));
