const API_BASE=(window.MERIDIAN_V9_CONFIG?.apiBase||'https://p01--achi-meridian--ttvk44grdlp7.code.run').replace(/\/$/,'');
const TOKEN_KEY='meridian.v8.readToken';
const FALLBACK=[
{id:'BTC-10X',symbol:'BTC',leverage:10,lower:45000,upper:100000,be:81208,liq:56499.2,tp:100000},{id:'BTC-5X',symbol:'BTC',leverage:5,lower:50000,upper:85000,be:81203.5,liq:52018.7,tp:85000},
{id:'ETH-5X',symbol:'ETH',leverage:5,lower:1750.02,upper:3000.03,be:2627.51,liq:1809.89,tp:3000.03},{id:'ETH-3X',symbol:'ETH',leverage:3,lower:1750.02,upper:3900,be:2627.46,liq:1694.86,tp:3900},
{id:'XRP-7X',symbol:'XRP',leverage:7,lower:.85,upper:1.8501,be:1.4475,liq:.9897,tp:1.8501},{id:'XRP-5X',symbol:'XRP',leverage:5,lower:.9,upper:2.3004,be:1.432,liq:.9854,tp:2.3004},
{id:'SOL-5X',symbol:'SOL',leverage:5,lower:55,upper:178.002,be:113.489,liq:70.053,tp:178.002},{id:'HBAR-5X',symbol:'HBAR',leverage:5,lower:.058,upper:.125,be:.07958,liq:.06078,tp:.125},
{id:'PEPE-4X',symbol:'PEPE',leverage:4,lower:.0000022,upper:.0000078,be:.000003864,liq:.0000025478,tp:.0000078},{id:'DOT-4X',symbol:'DOT',leverage:4,lower:.7,upper:2.2,be:1.137,liq:.768,tp:2.2},
{id:'ADA-3X',symbol:'ADA',leverage:3,lower:.13,upper:.45,be:.2258,liq:.137,tp:.45},{id:'SUI-3X',symbol:'SUI',leverage:3,lower:.6,upper:1.5,be:.8274,liq:.556,tp:1.5},{id:'AVAX-5X',symbol:'AVAX',leverage:5,lower:5.5,upper:11.8,be:8.488,liq:5.984,tp:11.8}];
const state={bots:FALLBACK,source:'REFERENCE',market:null,intel:null,portfolio:null,error:null,manual:{bitpanda:5408.27,ledger:776.74,okx:138.21}};
const $=s=>document.querySelector(s),num=v=>Number.isFinite(Number(v))?Number(v):null;
const money=x=>{x=num(x);if(x==null)return'—';if(x<.001)return'$'+x.toPrecision(5);return'$'+x.toLocaleString('de-DE',{maximumFractionDigits:2})};
function token(){try{return String(localStorage.getItem(TOKEN_KEY)||'').trim()}catch{return''}}
async function getJson(path){const r=await fetch(API_BASE+path,{cache:'no-store',headers:{accept:'application/json',...(token()?{authorization:'Bearer '+token()}:{})}});if(!r.ok)throw new Error('HTTP '+r.status);return r.json()}
function holdingValue(d,h){const q=num(h?.quantity),lp=num(d?.livePrices?.[h?.symbol]?.price),own=num(h?.price),stored=num(h?.value)??num(h?.valueUsd)??num(h?.usdValue);return q!=null&&q>=0&&lp>0?q*lp:q!=null&&q>=0&&own>0?q*own:stored||0}
function portfolioModel(d){const hs=Array.isArray(d?.portfolio?.holdings)?d.portfolio.holdings:[];const by={};for(const h of hs){const venue=String(h?.venue||'OTHER').toUpperCase(),v=holdingValue(d,h);by[venue]=(by[venue]||0)+v}const pionex=num(d?.portfolio?.pionexEquityUsd)??num(d?.pionexEquityUsd)??num(d?.pionexRisk?.equityUsd)??0;const bitpanda=state.manual.bitpanda,ledger=state.manual.ledger,okx=state.manual.okx;return{total:pionex+bitpanda+ledger+okx,pionex,bitpanda,ledger,okx}}
function normalizeLive(b){return{id:String(b.id||b.botId||b.name||b.symbol||'BOT'),symbol:String(b.symbol||b.asset||'').replace(/USDT$/,'').toUpperCase(),leverage:num(b.leverage??b.leverageX),lower:num(b.lowerRange??b.rangeLower??b.lowerPrice),upper:num(b.upperRange??b.rangeUpper??b.upperPrice),be:num(b.breakEvenPrice??b.breakevenPrice),liq:num(b.pionexLiquidationPrice??b.liquidationPrice??b.liqPrice),tp:num(b.takeProfit??b.tpPrice??b.tp),price:num(b.currentPrice??b.price),buffer:num(b.pionexLiqBufferPct??b.liqBufferPct??b.liquidationDistancePct),pnl:num(b.totalProfitUsd??b.totalProfitUSDT??b.totalProfit??b.pnlUsd??b.unrealizedPnlUsd??b.pnl),invest:num(b.investmentUsd??b.investmentUSDT??b.investment??b.investedUsd??b.invested),profitPct:num(b.totalProfitPct??b.profitPct??b.pnlPct),side:String(b.side||b.direction||'LONG').toUpperCase()}}
function mergeReference(live){const used=new Set;return FALLBACK.map(ref=>{const candidates=live.map((x,i)=>({x,i})).filter(o=>!used.has(o.i)&&o.x.symbol===ref.symbol&&o.x.side==='LONG');const hit=candidates.sort((a,b)=>Math.abs((a.x.leverage||0)-ref.leverage)-Math.abs((b.x.leverage||0)-ref.leverage))[0];if(!hit)return ref;used.add(hit.i);return{...ref,...Object.fromEntries(Object.entries(hit.x).filter(([,v])=>v!=null&&v!=='')),side:'LONG'}})}

function ema(v,p){if(v.length<p)return null;const k=2/(p+1);let e=v.slice(0,p).reduce((a,b)=>a+b,0)/p;for(let i=p;i<v.length;i++)e=v[i]*k+e*(1-k);return e}
function rsi(v,p=14){if(v.length<p+1)return null;let g=0,l=0;for(let i=1;i<=p;i++){const d=v[i]-v[i-1];g+=Math.max(0,d);l+=Math.max(0,-d)}g/=p;l/=p;for(let i=p+1;i<v.length;i++){const d=v[i]-v[i-1];g=(g*(p-1)+Math.max(0,d))/p;l=(l*(p-1)+Math.max(0,-d))/p}return l?100-100/(1+g/l):100}
function macd(v){if(v.length<35)return null;const series=p=>{const k=2/(p+1),o=[v[0]];for(let i=1;i<v.length;i++)o.push(v[i]*k+o[i-1]*(1-k));return o};const a=series(12),b=series(26),m=v.map((_,i)=>a[i]-b[i]);const k=2/10;let s=m[0];for(let i=1;i<m.length;i++)s=m[i]*k+s*(1-k);return{line:m.at(-1),signal:s,hist:m.at(-1)-s}}
function atr(rows,p=14){if(rows.length<p+1)return null;const t=[];for(let i=1;i<rows.length;i++)t.push(Math.max(rows[i].high-rows[i].low,Math.abs(rows[i].high-rows[i-1].close),Math.abs(rows[i].low-rows[i-1].close)));let a=t.slice(0,p).reduce((x,y)=>x+y,0)/p;for(let i=p;i<t.length;i++)a=(a*(p-1)+t[i])/p;return a}
async function binanceKlines(interval,limit){const r=await fetch('https://api.binance.com/api/v3/klines?symbol=BTCUSDT&interval='+interval+'&limit='+limit,{cache:'no-store'});if(!r.ok)throw new Error('BTC market HTTP '+r.status);return(await r.json()).map(x=>({openTime:+x[0],high:+x[2],low:+x[3],close:+x[4],closeTime:+x[6]}))}
function intel(rows4,rows1){const c4=rows4.map(x=>x.close),c1=rows1.map(x=>x.close),p=c4.at(-1),R4=rsi(c4),R1=rsi(c1),M4=macd(c4),M1=macd(c1),A=atr(rows4),e20=ema(c1,20),e50=ema(c1,50),e100=ema(c1,100),e200=ema(c1,200);const w=rows4.slice(-90),lo=Math.min(...w.map(x=>x.low)),hi=Math.max(...w.map(x=>x.high)),span=hi-lo,fibs=[.382,.5,.618,.786].map(f=>({f,price:hi-span*f})),near=fibs.reduce((a,b)=>Math.abs(b.price-p)<Math.abs(a.price-p)?b:a);const dailyBull=p>e200&&e20>e50,score=(dailyBull?30:0)+(R4>=42&&R4<=68?15:0)+(M4&&M4.hist>0?15:0)+(R1>=40&&R1<=70?10:0)+(M1&&M1.hist>0?10:0)+(Math.abs(p-near.price)<=Math.max(A*.75,p*.012)?20:0);return{price:p,rsi4:R4,rsi1:R1,macd4:M4,macd1:M1,atr:A,ema20:e20,ema50:e50,ema100:e100,ema200:e200,lo,hi,near,score,status:score>=70&&dailyBull?'RE-ENTRY READY':'WAIT FOR RETRACE'}}
async function syncIntel(){try{const [h4,d1]=await Promise.all([binanceKlines('4h',240),binanceKlines('1d',240)]);state.intel=intel(h4,d1)}catch(e){state.intel=null}}

function risk(b){const p=num(b.price)||num(b.be),liq=num(b.liq);if(!(p>0&&liq>0))return null;return b.side==='SHORT'?(liq-p)/p*100:(p-liq)/p*100}
function tpDist(b){const p=num(b.price)||num(b.be),tp=num(b.tp);if(!(p>0&&tp>0))return null;return b.side==='SHORT'?(p-tp)/p*100:(tp-p)/p*100}
function status(b){const r=risk(b),t=tpDist(b);if(t!=null&&t<=5)return['TP ZONE','tp'];if(r==null)return['CHECK','muted'];if(r<5)return['URGENT','danger'];if(r<10)return['MARGIN','danger'];if(r<18)return['WATCH','watch'];return['SAFE','safe']}
function botCard(b){const [st,tone]=status(b),r=risk(b),t=tpDist(b),pct=b.profitPct!=null?b.profitPct:(b.invest>0&&b.pnl!=null?b.pnl/b.invest*100:null);return `<article class="bot bot-v2"><div class="bothead"><div><h3>${b.symbol}</h3><small>${b.side||'LONG'} · ${b.leverage||'—'}x</small></div><span class="tag tone-${tone}">${st}</span></div><div class="profit-row"><div><span>INVEST</span><b>${b.invest==null?'—':money(b.invest)}</b></div><div><span>GESAMTPROFIT</span><b class="${b.pnl>0?'profit-pos':b.pnl<0?'profit-neg':''}">${b.pnl==null?'—':money(b.pnl)}${pct==null?'':' · '+(pct>=0?'+':'')+pct.toFixed(1)+'%'}</b></div></div><div class="bot-details"><span>PRICE <b>${money(b.price)}</b></span><span>BE <b>${money(b.be)}</b></span><span>LIQ <b>${money(b.liq)}</b></span><span>TP <b>${money(b.tp)}</b></span></div><div class="range-line">RANGE <b>${money(b.lower)} – ${money(b.upper)}</b></div><div class="risk"><i style="width:${Math.max(2,Math.min(100,r||0)*3)}%"></i></div><small class="distance">${r==null?'Liq —':r.toFixed(1)+'% Liq'} · ${t==null?'TP —':Math.max(0,t).toFixed(1)+'% TP'}</small></article>`}
function critical(){return [...state.bots].sort((a,b)=>(risk(a)??999)-(risk(b)??999))[0]}
function command(){const c=critical(),cs=c?status(c):['CHECK'],p=state.portfolio||{total:0,pionex:0,bitpanda:state.manual.bitpanda,ledger:state.manual.ledger,okx:state.manual.okx},tp=[...state.bots].filter(b=>{const x=tpDist(b);return x!=null&&x<=10});return `<section class="portfolio-hero"><div><span>GESAMTPORTFOLIO</span><strong>${p.total?money(p.total):'PIONEX SYNC'}</strong><small>Pionex + Bitpanda + Ledger + OKX Bot</small></div><div class="source-grid"><div><span>PIONEX</span><b>${p.pionex?money(p.pionex):'SYNC'}</b><small>COIN-M Bots</small></div><div><span>BITPANDA</span><b>${money(p.bitpanda)}</b><small>Spot / Earn</small></div><div><span>LEDGER</span><b>${money(p.ledger)}</b><small>Wallet</small></div><div><span>OKX</span><b>${money(p.okx)}</b><small>1 BTC DCA Bot</small></div></div></section><div class="grid compact-grid"><section class="metric"><span>PIONEX BOTS</span><b>${state.bots.length}</b><small>COIN-M Long</small></section><section class="metric"><span>RISK</span><b class="tone-${c?status(c)[1]:'muted'}">${c?c.symbol+' '+cs[0]:'—'}</b><small>${c&&risk(c)!=null?risk(c).toFixed(1)+'% Liq':'Sync'}</small></section><section class="metric"><span>TP RADAR</span><b>${tp.length}</b><small>≤10%</small></section><section class="metric"><span>BTC NEXT RANGE</span><b class="wait">${state.intel?state.intel.score+'/100':'SYNC'}</b><small>${state.intel?.status||'loading'}</small></section></div><section class="action compact-action"><span>NEXT ACTION</span><b>${c&&risk(c)!=null&&risk(c)<10?c.symbol+' Liquidationspuffer prüfen':'Bots halten · kein FOMO-Re-Entry'}</b></section><div class="section-title"><h2>BOT PULSE</h2><small>kritischste zuerst</small></div><div class="bots">${[...state.bots].sort((a,b)=>(risk(a)??999)-(risk(b)??999)).slice(0,6).map(botCard).join('')}</div>`}
function botGroup(title,subtitle,items){if(!items.length)return '';return `<section class="bot-group"><div class="group-head"><div><h2>${title}</h2><small>${subtitle}</small></div><b>${items.length}</b></div><div class="bots">${items.map(botCard).join('')}</div></section>`}
function bots(){const btc=state.bots.filter(b=>b.symbol==='BTC'),maj=state.bots.filter(b=>['ETH','SOL','XRP'].includes(b.symbol)),alt=state.bots.filter(b=>!['BTC','ETH','SOL','XRP'].includes(b.symbol));return `<section class="hero bot-hero"><div class="eyebrow">BOTS · ${state.source}</div><h1>PIONEX COIN-M</h1><p class="muted">${state.bots.length} aktive Long-Bots · gruppiert nach Rolle</p></section>${botGroup('BTC CORE','Hauptposition + Next-Range / Compounding',btc)}${botGroup('MAJORS','ETH · SOL · XRP',maj)}${botGroup('ALTCOINS','HBAR · PEPE · DOT · ADA · SUI · AVAX',alt)}`}
function market(){const i=state.intel;return `<section class="hero"><div class="eyebrow">MARKET + BODEN</div><h1>BTC REGIME</h1><p class="muted">1D entscheidet · 4h timet · BTCUSDT Spot</p></section><div class="grid"><section class="metric"><span>REGIME</span><b>${state.market||'SYNC'}</b><small>${i?money(i.price):'Market sync'}</small></section><section class="metric"><span>RSI</span><b>${i?i.rsi4.toFixed(1)+' · '+i.rsi1.toFixed(1):'SYNC'}</b><small>4h · 1D</small></section><section class="metric"><span>MACD HIST</span><b>${i&&i.macd4?i.macd4.hist.toFixed(1):'SYNC'}</b><small>4h momentum</small></section><section class="metric"><span>EMA 20 / 50</span><b>${i?money(i.ema20)+' / '+money(i.ema50):'SYNC'}</b><small>1D trend</small></section><section class="metric"><span>EMA 100 / 200</span><b>${i?money(i.ema100)+' / '+money(i.ema200):'SYNC'}</b><small>1D structure</small></section><section class="metric"><span>NEAREST FIB</span><b>${i?i.near.f.toFixed(3)+' · '+money(i.near.price):'SYNC'}</b><small>90 × 4h swing</small></section><section class="metric"><span>ATR 4H</span><b>${i?money(i.atr):'SYNC'}</b><small>Range width input</small></section><section class="metric"><span>NEXT RANGE SCORE</span><b class="${i&&i.status==='RE-ENTRY READY'?'tone-safe':'wait'}">${i?i.score+'/100':'SYNC'}</b><small>${i?i.status:'loading'}</small></section></div>`}
function research(){return `<section class="hero"><div class="eyebrow">RESEARCH</div><h1>NEXT RANGE LAB</h1><p class="muted">Keine Auswirkung auf echte Pionex-Bots.</p></section><section class="card"><b>BTC NEXT RANGE / COMPOUND V1</b><p>TP → Reload Reserve → WAIT FOR RETRACE → bestätigter Re-Entry.</p><small>Fib · RSI · MACD · EMA · ATR · Walk-forward / Holdout</small></section>`}
function more(){return `<section class="hero"><div class="eyebrow">MORE</div><h1>PORTFOLIO + SYSTEM</h1><p class="muted">Spot/Exchanges bleiben sekundär. Live-Quelle: ${state.source}.</p></section>`}
const render={command,bots,market,research,more};let current='command';
function go(v){current=v;document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.id==='view-'+v));document.querySelectorAll('#nav button').forEach(x=>x.classList.toggle('active',x.dataset.v===v));$('#view-'+v).innerHTML=render[v]()}
async function sync(){try{const payload=await getJson('/api/private/dashboard'),d=payload?.data||payload,live=Array.isArray(d?.pionexRisk?.bots)?d.pionexRisk.bots.map(normalizeLive):[];const longs=live.filter(b=>b.side==='LONG');state.bots=longs.length?mergeReference(longs):FALLBACK;state.source=live.length?'LIVE':'REFERENCE';state.market=String(d?.market?.regime||d?.btcRegime?.label||d?.regime?.label||'SYNC').toUpperCase();state.portfolio=portfolioModel(d);state.error=null}catch(e){state.error=e.message;state.source='REFERENCE'}go(current)}
document.querySelectorAll('#nav button').forEach(b=>b.onclick=()=>go(b.dataset.v));go('command');Promise.all([sync(),syncIntel()]).then(()=>go(current));setInterval(sync,30000);setInterval(()=>syncIntel().then(()=>{if(current==='market')go(current)}),60000);
