const BOTS=[
['BTC','10x',45000,100000,81208,56499.2,100000],['BTC','5x',50000,85000,81203.5,52018.7,85000],
['ETH','5x',1750.02,3000.03,2627.51,1809.89,3000.03],['ETH','3x',1750.02,3900,2627.46,1694.86,3900],
['XRP','7x',.85,1.8501,1.4475,.9897,1.8501],['XRP','5x',.90,2.3004,1.432,.9854,2.3004],
['SOL','5x',55,178.002,113.489,70.053,178.002],['HBAR','5x',.058,.125,.07958,.06078,.125],
['PEPE','4x',.0000022,.0000078,.000003864,.0000025478,.0000078],['DOT','4x',.70,2.20,1.137,.768,2.20],
['ADA','3x',.13,.45,.2258,.137,.45],['SUI','3x',.60,1.50,.8274,.556,1.50],['AVAX','5x',5.50,11.80,8.488,5.984,11.80]];
const $=s=>document.querySelector(s), money=x=>x<.01?'$'+x.toPrecision(4):'$'+x.toLocaleString('de-DE',{maximumFractionDigits:2});
function botCard(b){let[s,lev,lo,hi,be,liq,tp]=b;let buffer=Math.max(0,Math.min(100,(be-liq)/(be-lo)*55));return `<article class="bot"><div class="bothead"><h3>${s}</h3><span class="tag">LONG · ${lev}</span></div><small>COIN-M FUTURES GRID</small><div class="levels"><div><span>RANGE</span><b>${money(lo)} – ${money(hi)}</b></div><div><span>BREAK-EVEN</span><b>${money(be)}</b></div><div><span>LIQ</span><b>${money(liq)}</b></div><div><span>TP</span><b>${money(tp)}</b></div></div><div class="risk"><i style="width:${buffer}%"></i></div></article>`}
function command(){return `<section class="hero"><div class="eyebrow">COMMAND CENTER</div><h1>COIN-M · RISK FIRST</h1><p class="muted">Bots · Liquidation · TP · Reload · nächste Range</p></section><div class="grid"><section class="metric"><span>ACTIVE BOTS</span><b>${BOTS.length}</b><small>Pionex COIN-M Long</small></section><section class="metric"><span>BTC BOTS</span><b>2</b><small>85k / 100k TP</small></section><section class="metric"><span>RELOAD RESERVE</span><b>WAIT</b><small>erst nach realisiertem TP</small></section><section class="metric"><span>NEXT RANGE</span><b class="wait">ARMED</b><small>4h timing · 1D regime</small></section></div><section class="action"><span>NEXT ACTION</span><b>Bestehende Bots bis TP / Strukturbruch managen. Kein FOMO-Re-Entry.</b></section><div class="section-title"><h2>BOT PULSE</h2><small>nach Asset</small></div><div class="bots">${BOTS.slice(0,6).map(botCard).join('')}</div>`}
function bots(){return `<section class="hero"><div class="eyebrow">BOTS</div><h1>PIONEX COIN-M</h1><p class="muted">Aktive Strategiepositionen ersetzen die alte Exchange-zentrierte Hauptansicht.</p></section><div class="bots">${BOTS.map(botCard).join('')}</div>`}
function market(){return `<section class="hero"><div class="eyebrow">MARKET + BODEN</div><h1>BTC REGIME</h1><p class="muted">1D entscheidet · 4h timet</p></section><div class="grid"><section class="metric"><span>1D STRUCTURE</span><b>LIVE DATA</b><small>EMA 20/50/100/200 · HH/HL</small></section><section class="metric"><span>MOMENTUM</span><b>RSI + MACD</b><small>Divergenzen · Histogramm</small></section><section class="metric"><span>LIQUIDITY</span><b>FIB + VP</b><small>0.382 · 0.5 · 0.618 · 0.786</small></section><section class="metric"><span>DERIVATIVES</span><b>OI + FUNDING</b><small>nur frische belastbare Daten</small></section></div>`}
function research(){return `<section class="hero"><div class="eyebrow">RESEARCH</div><h1>NEXT RANGE LAB</h1><p class="muted">Research/Paper bleibt strikt getrennt von echten Pionex-Bots.</p></section><section class="card"><b>BTC NEXT RANGE / COMPOUND V1</b><p>TP → Reload Reserve → WAIT FOR RETRACE → bestätigter Re-Entry.</p><small>Fib · RSI · MACD · EMA · ATR · Walk-forward / Holdout</small></section>`}
function more(){return `<section class="hero"><div class="eyebrow">MORE</div><h1>PORTFOLIO + SYSTEM</h1><p class="muted">Spot-Bestände, Exchanges, Sync, Datenqualität und Einstellungen leben künftig hier – nicht mehr im Zentrum.</p></section>`}
const render={command,bots,market,research,more};function go(v){document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.id==='view-'+v));document.querySelectorAll('#nav button').forEach(x=>x.classList.toggle('active',x.dataset.v===v));$('#view-'+v).innerHTML=render[v]()}document.querySelectorAll('#nav button').forEach(b=>b.onclick=()=>go(b.dataset.v));go('command');